---
abstract: 'Flexible I18N using Locale::Maketext::Lexicon for Dancer apps'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Lexicon
requires:
  Dancer: 0
  Dancer::Plugin: 0
  File::Spec::Functions: 0
  I18N::LangTags: 0
  I18N::LangTags::Detect: 0
  I18N::LangTags::List: 0
  Package::Stash: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/clintongormley/Dancer-Plugin-Lexicon/issues
  repository: git://github.com/clintongormley/Dancer-Plugin-Lexicon.git
version: 0.02
